stages:
  - test
  - deploy

tests:python:
  stage: test
  image: python:3
  services:
    - postgres:9
  variables:
    POSTGRES_DB: zoudb
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: mysecretpassword
    DB_HOST: postgres
    MAIL_DEBUG: 1
    AUTH_STRATEGY: auth_local_no_password
    PREVIEW_FOLDER: ./data
  script:
    # Create thumbnail folder
    - mkdir -p $PREVIEW_FOLDER

    # Install requirements
    - pip install -r requirements.txt

    # Run Tests
    - PYTHONPATH=. py.test --ignore=tests/auth --ignore=tests/services/test_auth_service.py
  only:
    - pushes
  except:
    refs:
      - staging
      - master
      - tags
  tags:
    - test
