language: python
python:
  - "2.7"
  - "3.4"
  - "3.6"
services:
  - postgresql
addons:
  postgresql: "9.4"
  apt:
    sources:
      - sourceline: 'ppa:jonathonf/ffmpeg-3'
    packages: 
      - ffmpeg
install: 
  - "pip install -r requirements.txt"
before_script:
  - psql -c 'create database zoudb;' -U postgres
script: py.test
